### ISSUE TITLE
Autoreload some slides

### ISSUE THREAD

**Issue by decentninja** [datasektionen/Meta-TV#32]
The sl slide for example needs to reload. With the new caching this is never done.

**Comment by sootn** [comment]
Probably solved with a checkbox on each slide saying if it can be preloaded or not

**Comment by sootn** [comment]
Only needed for metasl, as that does not work any more I and Jesper have started a new one, https://github.com/sootn/metasl2, that will not need this :). Would be nice but not as important any more.
