### ISSUE TITLE
Popup om alkohol

### ISSUE THREAD

**Issue by Plongy** [datasektionen/Meta-TV#37]
Request från Ordf. att ha en popup som säger "Är du säker på att det inte bara är reklam för alkohol på bilden?" när man laddar upp bilder, detta för att påminna om att det ska finnas alkfria alternativ.

**Comment by sootn** [comment]
Smart!

**Comment by sootn** [comment]
Jättebra grej för någon ny på ior att implementera. Kanske inte som en popup, det är jobbigt, utan en text intill uploadknappen

**Comment by Plongy** [comment]
Kan vara lite jobbigt med en popup hela tiden, men det är viktigt att det inte bara står som info på sidan.

**Comment by pnyberg** [comment]
Elementärt åtgärdande gjort, dock extremt fult och troligtvis rätt påträngande då den påpekar det varje gång man commitar en bild.

**Comment by augustjanse** [comment]
Tog bort popuppen igen i 9ef5569b2f8fd0c5d6e166962f0404e45e0af1ef (med välsignelse av @sootn), men lämnade den röda texten.
