### ISSUE TITLE
Determine a new model of slide distribution

### ISSUE THREAD

**Issue by danielsson** [datasektionen/Meta-TV#39]
There seems to be a number of ideas how to distribute slides. We should decide upon how it should work before a number of dependent issues are resolved.

**Comment by Plongy** [comment]
I think that I and @sootn have talked about the following features:

* Have two categories of slides, informative and funny.
* A governor that:
 * Distributes slides evenly across screens
 * Allows for slides to be across several screens and syncs those.
 * Makes sure that at maximum 10% of the slides that are shown are funny.

**Comment by danielsson** [comment]
>Cooper -- Humour 75%. 
>
>TARS: 75%. Self destruct sequence in T minus 10 9 8... 
>
>Cooper: Let's make it 65℅.

**Comment by danielsson** [comment]
I have tried to run the system with different slides on each screens. I did not like the way it looked. It was wery cluttered, and some slides did not go so well together.

**Comment by Plongy** [comment]
:(

**Comment by sootn** [comment]
Color wise or...? Do they need to be themed?

**Comment by chav02** [comment]
I think it can get cluttered and confused with more than one random image up at the same time.
perhaps the cleanest and easiest to expect behavior is to show one object at a time, where an object can be images for all three screens, or image for one screen and black on the others.

**Comment by danielsson** [comment]
We should also be able to add multiple images to each slide, so that people can use the entire screen array if needed.

**Comment by danielsson** [comment]
This is what we came up with last thursday as I recall it:
* We scrap the channel concept in favor of slides, pages and screens.
* A slide consists of one or several pages, which could contain different content types.
* A page is what we today call a slide.
* A screen is a screen.

The content delivery strategy governor (haha) should pick one slide, and show each page on one screen. If there is only one page, show that on all screens. If a multiple-page slide is shown, show page one on screen one etc., and a simple data/media logotype on screens without a page.

**Comment by aronstrandberg** [comment]
"and a simple data/media logotype on screens without a page."

Rather repeat the first page instead?

**Comment by Plongy** [comment]
We talked about that possibility but decided that it would look weird if the middle slide is a continuation of the first slide, then we would get the entire picture one and a half time.

It's possible to upload a three picture slide with the same picture on the first and last screen if you don't want the data/media logo.

**Comment by pnyberg** [comment]
Shouldn't it be more clean if we, for a single-page-slide, showed the page in the middle and each chapters logotype on each side of the screen?

**Comment by aronstrandberg** [comment]
For a single page, I think having that page on all three screens is definitely the best option. With two page slides, that's up in the air.
