### ISSUE TITLE
Slideshow has wrong background color.

### ISSUE THREAD

**Issue by danielsson** [datasektionen/Meta-TV#40]
The slideshow has a bright background. It should be black.

**Comment by sootn** [comment]
Lol

**Comment by danielsson** [comment]
Im thinking that this is a perfect bite-sized issue for the next [hackertisdag](http://www.datasektionen.se/sektionen/namnder/ior/workshop)

**Comment by sootn** [comment]
Will rollback production...

**Comment by sootn** [comment]
Production now at 7d83f1a
