### ISSUE TITLE
"Ettan" can't log in to META-TV... :/ 

### ISSUE THREAD

**Issue by Dannymanificationer** [datasektionen/Meta-TV#58]
More specific info, contact decentninja.

**Comment by decentninja** [comment]
We made a workaround. Should be looked at again when we have a sane login or ldap system.

**Comment by Yopi** [comment]
Is working now, issue #65 relates to fixing this in a sane way.

**Comment by LudwikJaniuk** [comment]
Still not working, ettan here. The log in link sent me to the login page at first, but after logging in I just got back to the non-logged-in version of the page. Subsequent clicks just bounced me back. Cannot log in.

**Comment by JSimo** [comment]
This now applies to anyone that does not have already logged in to metatv once.
