### ISSUE TITLE
make gui daniil added not look ugly

### ISSUE THREAD

**Issue by pintjuk** [datasektionen/Meta-TV#6]

**Comment by sootn** [comment]
This is fixed right?

**Comment by Plongy** [comment]
Nope

**Comment by sootn** [comment]
What is missing? I mean we could do a complete rewrite and that would be better. But why?

**Comment by Plongy** [comment]
Needs at least a partial rewrite now that we've added slides to make the GUI more comprehensive.

Want 1.0 to be a kind of working stable version
