### ISSUE TITLE
Custom slide duration

### ISSUE THREAD

**Issue by aronstrandberg** [datasektionen/Meta-TV#64]
Would be nice to set different duration on slides. Perhaps only when filtering by tags (it's useful during events) but not so nice when someone sets 5 minutes custom time during the day)

**Comment by LudwikJaniuk** [comment]
This seems like it could be done with some kind of priority levels? Everyone is subjective on how mych time their own slide deserves, but if you decide say 3 "priority levels" and explain those people should adapt.

I think.

**Comment by Yopi** [comment]
Duplicate of #54
