### ISSUE TITLE
Reverse sorting of pages

### ISSUE THREAD

**Issue by aronstrandberg** [datasektionen/Meta-TV#74]
Newly created slides are often the ones you need to take action on, so I think reversing the order of them on the start page would be nice. Thoughts?

/cc @JSimo @danielsson

**Comment by luminiusa** [comment]
låter nice

Joel Ekelöf

2016-02-28 18:31 GMT+01:00 Aron Strandberg <notifications@github.com>:

**Comment by JSimo** [comment]
Sounds like a good idea. For now when #73 is merged you will automatically scroll to the newly created slide.

**Comment by aronstrandberg** [comment]
Is this still not an issue? @LudwikJaniuk

**Comment by LudwikJaniuk** [comment]
Apologies, thought #73 solved the issue. So, chronilogic reverse sorting on frontpage still does not exist.
